//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanDoGiaDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string username { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string @class { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string mail { get; set; }
        public string image { get; set; }
    }
}
